project:
  type: website
  output-dir: docs

filters:
- courseformat ### for custom callouts
editor: source
bibliography: book.bib

format:
  html:
    theme: ### can only point to scss, not css
      - cosmo
      - lh-style2.scss ### seems easier than css?
    css: lh-style.css   ### doesn't render NCEAS logo if put in scss file?
    toc: true
    number-sections: true
    title-block-banner: "blue" ### need something here to "turn on" the title-block-banner

website:
  title: "COURSE_TITLE (COURSE_DATES)"
  reader-mode: false
  repo-url: COURSE_REPO

  favicon: logo-lh-hex.png # learning hub logo on browser tab

  bread-crumbs: false ### NEW keep header clean
  navbar: ### NEW inspired by Nick's site
    right:
      - text: "Instructors"
        menu:
          - text: "Casey O'Hara"
            href: https://www.oharascience.com/
      - icon: github
        href: COURSE_REPO
        aria-label: GitHub

  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: COURSE_URL

  contents:
    - index.qmd # preface
    SESSION_LINKS

  page-footer:
    center: "Copyright \u00a9 2024, NCEAS"
    ### NCEAS main website footer:
    # center: "\u00a9 The Regents of the University of California, All Rights Reserved"
    # could also include license info?
    background: "#0C4537"


