project:
  type: book
  output-dir: docs

book:
  title: "COURSE_TITLE"
  subtitle: "COURSE_DATES"
  reader-mode: false

  favicon: logo-lh-hex.png # learning hub logo on browser tab

  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: COURSE_URL

  chapters:
    - index.qmd # preface
    SESSION_LINKS

  page-footer:
    center: "Copyright \u00a9 2024, NCEAS"
    ### NCEAS main website footer:
    # center: "\u00a9 The Regents of the University of California, All Rights Reserved"
    # could also include license info?
    background: "#0C4537"


bibliography: book.bib

format:
  html:
    theme: cosmo
    css: style.css
    title-block-banner: "blue" ### need to invoke this to "turn on" the title-block-banner
    ### add css to tighten the margins? add an NCEAS or LH logo in the header?

editor: source
