project:
  type: book
  output-dir: docs

book:
  title: "COURSE_TITLE"
  subtitle: "COURSE_DATES"
  reader-mode: false

  # NoteHD: cover image is not working
  # cover-image: cover.png
  # cover-image-alt: "Learning Hub logo in the shape of a hexagon with a bee in the center"

  favicon: cover.png # learning hub logo

  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: COURSE_URL

  chapters:
    - index.qmd # preface
    SESSION_LINKS



bibliography: book.bib

format:
  html:
    theme: cosmo
    css: style.css
    title-block-banner: "#0b5f4acc" ### doesn't exactly match header color in style.css...?
    title-block-banner-color: "white"
    ### add css to tighten the margins? add an NCEAS or LH logo in the header?
  # Note HD: latex rendering issues, maybe with column-margin
  # pdf:
  #   documentclass: scrreprt

editor: source
